### ISSUE TITLE
String for mocks looks weird

### ISSUE THREAD

**Issue by eskimoblood** [trayio/enzyme-to-json#12]
I use Jest to mock out some child components, with the `react-test-renderer` I got 

    <mocked someProps="someString" />

using `enzyme` and `shallowToJson` I got:

    <function (props) {return (/* istanbul ignore next */_react2.default.createElement( /* istanbul ignore next */'mocked', /* istanbul ignore next */_extends({ originalComponent: componentName }, props), props.children));} someProps="someString" />

Do you think its possible to recognise mocks and render they just like the `react-test-renderer`.

**Comment by adriantoine** [comment]
Hi, thanks for raising the bug, I will have a look!

**Comment by adriantoine** [comment]
@eskimoblood Can you give me more details about your test? How exactly are you mocking the component?

**Comment by adriantoine** [comment]
In one of my project, I'm using `enzyme-to-json` and Jest mocking like that:
```js
jest.mock('../Field', () => {
    return function Field(props) {
        return props.children;
    };
});
```
and it works fine with `Field` as a display name.

But I'm interested in your issue, can you provide more details?

**Comment by eskimoblood** [comment]
I'm using the approach from thus [gist](https://gist.github.com/evansiroky/89deb7759ae487abb5fed6d1dfdfce84#file-project-test-js)

**Comment by eskimoblood** [comment]
But let me try your approach, maybe this fix the problem.

**Comment by adriantoine** [comment]
Cool, thanks for the link, I'm looking at it!

**Comment by adriantoine** [comment]
Ok so I've just tried that (basically just copying from your link):
```js
function mockComponent(componentName) {
    return props => {
        return (
            <mocked originalComponent={componentName} {...props}>{props.children}</mocked>
        );
    };
}

jest.mock('./fixtures/mocked-component', () => { return mockComponent('Icon'); });

import MockedComponent from './fixtures/mocked-component';

it('converts a mocked component', () => {
    const shallowed = shallow(
        <MockedComponent className="class"><strong>Hello!</strong></MockedComponent>
    );
    expect(shallowToJson(shallowed)).toMatchSnapshot();
});
```
and the snapshot output is:
```js
exports[`test converts a mocked component 1`] = `
<mocked
  className="class"
  originalComponent="Icon">
  <strong>
    Hello!
  </strong>
</mocked>
`;
```
which seems ok 🤔

**Comment by bsr203** [comment]
I too had transpiled code in my snapshot even with react-test-renderer https://github.com/facebook/jest/issues/1756

though it is closed, @cpojer acknowledge it was reported by others too.

**Comment by eskimoblood** [comment]
I just move to 
```
jest.mock('../../components', () => {
  return {
    TextField: () => 'TextField',
    DatePicker: () => 'DatePicker'
  }
});
```

as suggested in the comments of the gist and it works. So just close the issue. Thanks for your help.

**Comment by adriantoine** [comment]
Ok thanks for the insight @bsr203, that's strange 🤔

@eskimoblood I'm glad it works with you 😊 I'm still curious of what was causing that.
