### ISSUE TITLE
Snapshot with instrumentation code in it

### ISSUE THREAD

**Issue by bsr203** [trayio/enzyme-to-json#13]
Just though this maybe more relevant here as @kentcdodds says it doesn't happen with `react-test-renderer`. Hope you can identify the cause in this case as it only happens with `enzyme-to-json`.

please see https://github.com/facebook/jest/issues/1780 for details

**Comment by adriantoine** [comment]
Hi,
Thanks for the link, @trayio got mentioned but I don't get notifications for these are that's my company. I'll have a look.
