### ISSUE TITLE
shallowToJson with nested components throws TypeError

### ISSUE THREAD

**Issue by zenfe** [trayio/enzyme-to-json#7]
With the change from #1 I get the following error when using `shallowToJson` with nested components:

> TypeError: Cannot read property 'type' of undefined
> at shallowToJson (node_modules/enzyme-to-json/build/index.js:57:22)

**Comment by adriantoine** [comment]
Thanks for reporting the issue! Can you give an actual example that reproduce the issue?

**Comment by adriantoine** [comment]
Ok I've been able to reproduce the issue, I'm working on it!

**Comment by adriantoine** [comment]
@zenfe Fixed in #8, I'm publishing a new version, sorry for the inconvenience!

**Comment by adriantoine** [comment]
The fix is included in `v1.1.1`, just published 🎉
